version: '3.8'
services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro-container
    restart: unless-stopped
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  caddy:
    image: caddy:alpine
    container_name: caddy
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
